# -*- coding: utf-8 -*-
"""
Created on Sat Jan 23 18:01:22 2016

@author: Lluís Carreras González

Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following 
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def triangular(num):
    """
    Create the tringular number Tn = n(n+1)/2 for the given number.
    """
    
    return int(0.5 * num * (num + 1))
    

def pentagonal(num):
    """
    Create the pentagonal number Pn = n(3n-1)/2 for the given number.
    """
    
    return int(0.5 * num * (3 * num - 1))
    
    
def hexagonal(num):
    """
    Create the hexagonal number Hn = n(2n-1) for the given number.
    """
    
    return int(num * (2 * num - 1))
    
    
n_max = 100000

tris = [triangular(n) for n in range(n_max)]
pentas = [pentagonal(n) for n in range(n_max)]
hexas = [hexagonal(n) for n in range(n_max)]



for tri in tris:
    if tri in pentas and tri in hexas and tri > 40755:
        print(tri, "\t", tris.index(tri))
        break

