# -*- coding: utf-8 -*-
"""
Created on Thu Jan  7 17:01:46 2016
@author: Lluís Carreras

Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

"""

def even_Fibonacci_numbers(limit):
    fibonacci_a = 1
    fibonacci_b = 2
    total = 2
    while fibonacci_b <= limit:
        next_fibonacci = fibonacci_a + fibonacci_b
        if (next_fibonacci % 2 == 0):
            total += next_fibonacci
        fibonacci_a, fibonacci_b = fibonacci_b, next_fibonacci
    return total
    

print(even_Fibonacci_numbers(4000000))
